# Date    : 2019/07/16
# Author  : Snow Yang
# Mail    : yangsw@mxchip.com

EXTRA_POST_BUILD_TARGETS += $(MXOS_ALL_BIN_OUTPUT_FILE) pick
ADD_MD5_SCRIPT := $(SOURCE_ROOT)/mxos/platform/MCU/mx1290/script/add_md5.py
OTA_BIN_OUTPUT_FILE := $(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.ota$(BIN_OUTPUT_SUFFIX))

TEXT_OUTPUT_FILE           :=$(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.text.bin)
DATA_OUTPUT_FILE           :=$(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.data.bin)

pick: 
	$(OBJCOPY) -j .xip_image2.text -Obinary $(LINK_OUTPUT_FILE) $(TEXT_OUTPUT_FILE)
	$(OBJCOPY) -j .ram_image2.entry -j .ram_image2.text -j .ram_image2.data -Obinary $(LINK_OUTPUT_FILE) $(DATA_OUTPUT_FILE)
	$(PYTHON) mxos/platform/MCU/mx1290/tools/pick.py $(TEXT_OUTPUT_FILE) $(DATA_OUTPUT_FILE) $(BIN_OUTPUT_FILE)
	$(RM) $(TEXT_OUTPUT_FILE) $(DATA_OUTPUT_FILE)
	$(CP) $(BIN_OUTPUT_FILE) $(OTA_BIN_OUTPUT_FILE)
	$(PYTHON) $(ADD_MD5_SCRIPT) $(OTA_BIN_OUTPUT_FILE)
	
# Required to build Full binary file
GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT:= $(SCRIPTS_PATH)/gen_common_bin_output_file.py

MXOS_ALL_BIN_OUTPUT_FILE :=$(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.all$(BIN_OUTPUT_SUFFIX))

$(MXOS_ALL_BIN_OUTPUT_FILE): pick
	$(QUIET)$(ECHO) Generate $(MXOS_ALL_BIN_OUTPUT_FILE) ...
	$(QUIET)$(RM) $(MXOS_ALL_BIN_OUTPUT_FILE)
	$(PYTHON) $(GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT) -o $(MXOS_ALL_BIN_OUTPUT_FILE) -f 0x000000 $(MXOS_OS_PATH)/platform/MCU/mx1290/image/boot.bin          
	$(PYTHON) $(GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT) -o $(MXOS_ALL_BIN_OUTPUT_FILE) -f 0x018000 $(BIN_OUTPUT_FILE)
	$(PYTHON) $(GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT) -o $(MXOS_ALL_BIN_OUTPUT_FILE) -f 0x100000 $(MXOS_OS_PATH)/platform/MCU/mx1290/image/ate.bin
	