NAME := EMC3380

MODULE := emc3380
HOST_MCU_FAMILY := mx1410

$(NAME)_COMPONENTS += platform/MCU/$(HOST_MCU_FAMILY)
$(NAME)_SOURCES := module.c 
# Global includes
GLOBAL_INCLUDES  := .
GLOBAL_DEFINES := QC_TEST_BLE_SCAN

GLOBAL_DEFINES += KV_CONFIG_TOTAL_SIZE=(16*1024)

JTAG := jlink_swd
