/**
 ******************************************************************************
 * @file    module.h
 * @author  Snow Yang
 * @version V1.0.0
 * @date    02-Sept-2019
 * @brief   This file provides current module's pin and partiton define.
 ******************************************************************************
 */

#ifndef __MOUDLE_H__
#define __MOUDLE_H__

#include "peripheral_names.h"

#define HARDWARE_REVISION "1.0"
#define DEFAULT_NAME "MX1290"
#define MODEL "MX1290"
#define MCU_CLOCK_HZ 52000000

/*
This Table is Generated by MAsciiTable Written by Snow Yang at Fri Sep  6 15:18:57 2019
+------------+-------+-------+-------------+------------+-------------+-------+
| Module Pin | GPIO  | PWM   |   UART      |   I2C      |    SPI      |  SWD  |
+------------+-------+-------+-------------+------------+-------------+-------+
|     3      | PA_14 | PWM_0 |             |            |             | SWCLK |
+------------+-------+-------+-------------+------------+-------------+-------+
|     4      | PA_15 | PWM_1 |             |            |             | SWDIO |
+------------+-------+-------+-------------+------------+-------------+-------+
|     7      | PA_22 | PWM_5 | RTS(UART_0) | SCL(I2C_0) | MISO(SPI_1) |       |
+------------+-------+-------+-------------+------------+-------------+-------+
|     8      | PA_19 |       | CTS(UART_0) | SDA(I2C_0) | CS(SPI_1)   |       |
+------------+-------+-------+-------------+------------+-------------+-------+
|     9      | PA_23 | PWM_0 | TXD(UART_0) | SDA(I2C_1) | MOSI(SPI_1) |       |
+------------+-------+-------+-------------+------------+-------------+-------+
|     10     | PA_18 |       | RXD(UART_0) | SCL(I2C_1) | CLK(SPI_1)  |       |
+------------+-------+-------+-------------+------------+-------------+-------+
|     12     | PA_0  | PWM_2 |             |            |             |       |
+------------+-------+-------+-------------+------------+-------------+-------+
|     13     | PA_12 | PWM_3 |             |            |             |       |
+------------+-------+-------+-------------+------------+-------------+-------+
|     14     | PA_5  | PWM_4 |             |            |             |       |
+------------+-------+-------+-------------+------------+-------------+-------+
|     19     | PA_11 |       |             |            |             |       |
+------------+-------+-------+-------------+------------+-------------+-------+
|     21     | PA_30 | PWM_3 | TXD(UART_2) | SDA(I2C_0) |             |       |
+------------+-------+-------+-------------+------------+-------------+-------+
|     22     | PA_29 | PWM_4 | RXD(UART_2) | SCL(I2C_0) |             |       |
+------------+-------+-------+-------------+------------+-------------+-------+
|     23     | PA_8  |       |             |            |             |       |
+------------+-------+-------+-------------+------------+-------------+-------+
*/

enum
{
  MODULE_PIN_1 = PA_14,
  MODULE_PIN_2 = PA_15,
  MODULE_PIN_7 = PA_22,
  MODULE_PIN_8 = PA_19,
  MODULE_PIN_9 = PA_23,
  MODULE_PIN_10 = PA_18,
  MODULE_PIN_12 = PA_0,
  MODULE_PIN_13 = PA_12,
  MODULE_PIN_14 = PA_5,
  MODULE_PIN_19 = PA_11,
  MODULE_PIN_21 = PA_30,
  MODULE_PIN_22 = PA_29,
  MODULE_PIN_23 = PA_8,
  MODULE_PIN_NC = PIN_NC,
};

/*
This Table is Generated by MAsciiTable Written by Snow Yang at Tue Sep 17 11:34:27 2019
+----------------+-------------+---------+
| Partition Name | PHY Address |  Size   |
+----------------+-------------+---------+
|   Bootloader   |    0x00     | 0x13000 |
+----------------+-------------+---------+
|  Information   |   0x13000   | 0x1000  |
+----------------+-------------+---------+
|       KV       |   0x14000   | 0x4000  |
+----------------+-------------+---------+
|  Application   |   0x18000   | 0xE8000 |
+----------------+-------------+---------+
|    OTA/ATE     |  0x100000   | 0xE8000 |
+----------------+-------------+---------+
|      User      |  0x1E8000   | 0x18000 |
+----------------+-------------+---------+
*/

enum
{
  MODULE_PARTITION_BOOTLOADER,
  MODULE_PARTITION_INFO,
  MODULE_PARTITION_KVRO,
  MODULE_PARTITION_APPLICATION,
  MODULE_PARTITION_OTA_TEMP,
  MODULE_PARTITION_ATE = MODULE_PARTITION_OTA_TEMP,
  MODULE_PARTITION_USER,
  MODULE_PARTITION_KV = MODULE_PARTITION_USER,
  MODULE_PARTITION_MAX,
  MODULE_PARTITION_NONE,
};

#endif
